import type { Metadata } from "next";
import localFont from "next/font/local";
import { Manrope, Pacifico} from "next/font/google"; // Import Roboto from Google Fonts
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope", // Add a CSS variable for Roboto
  weight: ["200","300","400","500","600","700","800"], // Specify desired font weights (e.g., 400 for regular, 700 for bold)
});
const pacifico = Pacifico({
  subsets: ["latin"],
  variable: "--font-pacifico", // Add a CSS variable for Pacifico
  weight: "400", // Pacifico supports only this weight
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${manrope.variable} ${pacifico.variable}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
